import type { Metadata } from 'next';
import '@/styles/globals.css';
import Header from '@/components/header';
import { grandi, ultra, berkshire } from './styles/fonts';

export const metadata: Metadata = {
  title: 'The New York Times - Bestsellers',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ultra.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
